-- AlterTable
ALTER TABLE `Sale` ADD COLUMN `status` ENUM('COMPLETED', 'VOIDED') NOT NULL DEFAULT 'COMPLETED',
    ADD COLUMN `voidedAt` DATETIME(3) NULL,
    ADD COLUMN `voidedById` INTEGER NULL;

-- AddForeignKey
ALTER TABLE `Sale` ADD CONSTRAINT `Sale_voidedById_fkey` FOREIGN KEY (`voidedById`) REFERENCES `User`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;
